// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalSystemProcedures.DBContext;

namespace PersonalSystemProcedures.Migrations
{
    [DbContext(typeof(TuShanContext))]
    [Migration("20190813075037_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PersonalSystemProcedures.Models.MobileModels.DbModel.Admin", b =>
                {
                    b.Property<string>("AdminId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdminName")
                        .IsRequired();

                    b.Property<string>("AdminPasswd")
                        .IsRequired();

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("PersonalSystemProcedures.Models.MobileModels.DbModel.LostInfo", b =>
                {
                    b.Property<string>("LostInfoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LostInfoPic");

                    b.Property<string>("LostInfos");

                    b.Property<string>("LostName");

                    b.Property<DateTime>("LostTime");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("States");

                    b.Property<string>("UserID");

                    b.Property<string>("UserName");

                    b.HasKey("LostInfoID");

                    b.ToTable("LostInfors");
                });

            modelBuilder.Entity("PersonalSystemProcedures.Models.MobileModels.DbModel.User", b =>
                {
                    b.Property<string>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserCollege");

                    b.Property<string>("UserEmail");

                    b.Property<string>("UserHPortraitURL");

                    b.Property<string>("UserIndiSignature");

                    b.Property<string>("UserName");

                    b.Property<bool>("UserOnline");

                    b.Property<string>("UserPasswd");

                    b.Property<string>("UserPhoneNum");

                    b.Property<string>("UserSex");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
